// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOocD-FeG1aIxhpxEIJJxORDVat7EAblE',
    appId: '1:354019570021:android:a9b70fef66d0d86f18b18c',
    messagingSenderId: '354019570021',
    projectId: 'not-app-c341e',
    storageBucket: 'not-app-c341e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy-lsvUrcnCI5UCS9a-8HLXC9B9SNkHP0',
    appId: '1:354019570021:ios:1e6abdf2042e32ff18b18c',
    messagingSenderId: '354019570021',
    projectId: 'not-app-c341e',
    storageBucket: 'not-app-c341e.appspot.com',
    androidClientId: '354019570021-a019q8p6vcngcqapf4q1sdh555tij3f5.apps.googleusercontent.com',
    iosClientId: '354019570021-a4pop288k7hia2fto7pep7ljb84308o9.apps.googleusercontent.com',
    iosBundleId: 'com.agprogramming.not',
  );
}
